apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-a-deploy
spec:
  replicas: 1
  selector:    
    matchLabels:
       app: server-a 
  template:
    metadata:
      name: pod-a
      labels:
        app: server-a
    spec:
      containers:
        - name: con-a
          image: moshe5434/black-project:v1
          ports:
            - containerPort: 8000
          env:
            - name: SERVER_B_HOST
              value: server-b
            - name: SERVER_B_PORT
              value: "8000"
            - name: SERVER_B_TIMEOUT
              value: "5"
            - name: "INFO_GEOLOCATION_WEBSITE"
              value: "http://ip-api.com/json/"
            - name: "FIELDES"
              value: "?fields=status,message,lat,lon,query"
            
             