apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-a
    labels: 
        app: deploy-server-a 
spec:
  replicas: 1
  selector:    
    matchLabels:
       app: api-a 
  template:
    metadata:
      labels:
        app: api-a
    spec:
      containers:
        - name: con-a
          image: moshe5434/black-project:v1
          ports:
            - containerPort: 8000
            
             