apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-a-deploy
spec:
  replicas: 1
  selector:    
    matchLabels:
       app: server-a 
  template:
    metadata:
      name: pod-a
      labels:
        app: server-a
    spec:
      containers:
        - name: con-a
          image: moshe5434/black-project:v1
          ports:
            - containerPort: 8000
            
             