apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  clusterIP: None                   # headless Service for StatefulSet
  selector:
    app: redis-label
  ports:
    - port: 6379
      targetPort: 6379