apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-b-label 
  template:
    metadata:
      labels:
        app: server-b-label
    spec:
      containers:
      - name: server-b-pod
        image: aharonsegal/server-b:latest
        env:
            - name: REDIS_HOST
              value: "redis-svc"         # name of Redis Service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
        ports:                    # not strictly required, but very good practice
          -  containerPort: 8080  # matches uvicorn command inside the container
        # best practice
        # resources:
        #   requests:
        #     cpu: "50m"
        #     memory: "64Mi"
        #   limits:
        #     cpu: "500m"
        #     memory: "100Mi"
