# server-b_Dockerfile
FROM python:3.12-slim

# Working directory inside the container
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# to image app copy all content from local app
COPY app ./app

EXPOSE 8000

# Default Redis env (can be overridden via .env / compose)
ENV REDIS_HOST=redis \
    REDIS_PORT=6379 \
    REDIS_DB=0

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]