version: "3.9"

services:
  redis:
    build:
      context: ./server-b
      dockerfile: Dockerfile.redis
    container_name: redis
    ports:
      - "6379:6379"          
    restart: unless-stopped

  server-b:
    build:
      context: ./server-b
      dockerfile: app/Dockerfile
    container_name: server-b
    env_file:
      - .env      
    depends_on:
      - redis
    ports:
      - "8000:8000"        
    restart: unless-stopped